services:
  - type: web
    name: bulkedit
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: cd server && npx prisma migrate deploy && npm start
    envVars:
      - key: SHOPIFY_API_KEY
        sync: false
      - key: SHOPIFY_API_SECRET
        sync: false
      - key: SCOPES
        value: read_products,write_products
      - key: SHOPIFY_APP_URL
        value: https://bulkedit-n5ls.onrender.com
      - key: HOST
        value: https://bulkedit-n5ls.onrender.com
      - key: DATABASE_URL
        sync: false
      - key: NODE_ENV
        value: production
      - key: MAX_PRODUCTS_PER_RUN
        value: 500
      - key: MAX_MEDIA_DELETES_PER_RUN
        value: 5000
